LOCAL_PATH := $(call my-dir)
 
include $(CLEAR_VARS)
LOCAL_MODULE = i2c-tools
LOCAL_C_INCLUDES += $(LOCAL_PATH) $(LOCAL_PATH)/include
LOCAL_SRC_FILES = tools/i2cbusses.c tools/util.c
LOCAL_SDK_VERSION := 19
include $(BUILD_STATIC_LIBRARY)
 
include $(CLEAR_VARS)
LOCAL_MODULE = i2cdetect
LOCAL_SRC_FILES = tools/i2cdetect.c
LOCAL_CPPFLAGS += -DANDROID
LOCAL_STATIC_LIBRARIES = i2c-tools
LOCAL_C_INCLUDES += $(LOCAL_PATH) $(LOCAL_PATH)/include
LOCAL_SDK_VERSION := 19
include $(BUILD_EXECUTABLE)
 
include $(CLEAR_VARS)
LOCAL_MODULE = i2cget
LOCAL_SRC_FILES = tools/i2cget.c
LOCAL_CPPFLAGS += -DANDROID
LOCAL_STATIC_LIBRARIES = i2c-tools
LOCAL_C_INCLUDES += $(LOCAL_PATH) $(LOCAL_PATH)/include
LOCAL_SDK_VERSION := 19
include $(BUILD_EXECUTABLE)
 
include $(CLEAR_VARS)
LOCAL_MODULE = i2cset
LOCAL_SRC_FILES = tools/i2cset.c
LOCAL_CPPFLAGS += -DANDROID
LOCAL_STATIC_LIBRARIES = i2c-tools
LOCAL_C_INCLUDES += $(LOCAL_PATH) $(LOCAL_PATH)/include
LOCAL_SDK_VERSION := 19
include $(BUILD_EXECUTABLE)
 
include $(CLEAR_VARS)
LOCAL_MODULE = i2cdump
LOCAL_SRC_FILES = tools/i2cdump.c
LOCAL_CPPFLAGS += -DANDROID
LOCAL_STATIC_LIBRARIES = i2c-tools
LOCAL_C_INCLUDES += $(LOCAL_PATH) $(LOCAL_PATH)/include
LOCAL_SDK_VERSION := 19
include $(BUILD_EXECUTABLE)

